# Generated by Django 5.2.3 on 2025-07-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('status', models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '暂停中'), (3, '已完成'), (4, '已终止')], default=0, verbose_name='项目状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '项目project',
                'verbose_name_plural': '项目',
                'ordering': ['-create_time'],
            },
        ),
    ]
